name: Generate contribution snake

on:
  schedule:
    - cron: "0 0 * * *"  # Runs once daily

  workflow_dispatch:  # Allows manual execution

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake animation
        uses: Platane/snk@master
        with:
          github_user_name: PPathu
          svg_out_path: dist/github-contribution-grid-snake.svg

      - name: Push snake animation to GitHub
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
