name: Generate contribution snake
on:
  schedule:
    - cron: "0 0 * * *"  # Runs every day

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@master
        with:
          github_user_name: PPathu
          svg_out_path: dist/github-contribution-grid-snake.svg
      - name: Push Snake
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: output
          build_dir: dist
